In [21]:
import pandas as pd
import numpy as np

In [1]:
ORGS_INFO = [{'Logo': 'https://ugc.production.linktr.ee/0114a22c-cc95-42af-9cf8-0d9af874a026_Untitled-design.png?io=true&size=avatar-v3_0', 
             'Name': 'Austin Bodybuilding (ABB)', 'Categories': ['Fitness', 'Social'], 'Description': 'A community of bodybuilders, gym-goers, and like-minded people!'}, 
             {'Logo': 'https://www.txconvergent.org/static/media/logo.4f3c2372.png', 
             'Name': 'Texas Convergent', 'Categories': ['Computer Science', 'Technology'], 'Description': 'Texas Convergent is an entrepreneurial, product-building organization at UT Austin. We provide students the necessary skills and resources to drive the future of innovation through a hands-on, project-based curriculum.'}, 
             {'Logo': 'https://lh3.googleusercontent.com/z6m1_-gQz8GmTdidDebdEncGMXp3zUCAA4S9cnnpFo_-IE87b6FSofSfNZxKGvQvbb9mS6jzifh2IO3V53rniCD3vhphmebMMkgLlygtH2fe8JrcQd2ib-1WVHhWkZv2Lw=w1280', 'Name': 'Machine Learning and Data Science Club (MLDS)', 'Categories': ['Computer Science', 'Technology'], 'Description': 'We promote data science and machine learning through our general meetings every Tuesday at 7 pm. These meetings include technical workshops, career advice, industry speakers, and socials. We also host the Deep Learning Workshop Series, Long Competition, and Datahack.'}, {'Logo': 'https://www.cs.utexas.edu/~wics/images/wicslogo24.png', 'Name': 'Women in Computer Science (WICS)', 'Categories': ['Computer Science', 'Technology'], 'Description': 'Women in Computer Science is a non-profit organization dedicated to building a community of women in Computer Science.'}]

In [2]:
ORGS_INFO

[{'Logo': 'https://ugc.production.linktr.ee/0114a22c-cc95-42af-9cf8-0d9af874a026_Untitled-design.png?io=true&size=avatar-v3_0',
  'Name': 'Austin Bodybuilding (ABB)',
  'Categories': ['Fitness', 'Social'],
  'Description': 'A community of bodybuilders, gym-goers, and like-minded people!'},
 {'Logo': 'https://www.txconvergent.org/static/media/logo.4f3c2372.png',
  'Name': 'Texas Convergent',
  'Categories': ['Computer Science', 'Technology'],
  'Description': 'Texas Convergent is an entrepreneurial, product-building organization at UT Austin. We provide students the necessary skills and resources to drive the future of innovation through a hands-on, project-based curriculum.'},
 {'Logo': 'https://lh3.googleusercontent.com/z6m1_-gQz8GmTdidDebdEncGMXp3zUCAA4S9cnnpFo_-IE87b6FSofSfNZxKGvQvbb9mS6jzifh2IO3V53rniCD3vhphmebMMkgLlygtH2fe8JrcQd2ib-1WVHhWkZv2Lw=w1280',
  'Name': 'Machine Learning and Data Science Club (MLDS)',
  'Categories': ['Computer Science', 'Technology'],
  'Description': 'W

In [6]:
pcts = []

for org in ORGS_INFO: 
    org_cats = set(org["Categories"])
    common = my_interests.intersection(org_cats)
    pcts.append(len(common) / len(my_interests))

pcts

[0.25, 0.5, 0.5, 0.5]

I'd like to also incorporate more semantics when it comes to recommendaions, bc simply doing an intersection is a bit lame. I added club descriptions to the dataset as well, so I can use those in the recommendations.

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [8]:
org_descriptions = [org["Description"] for org in ORGS_INFO]
org_descriptions

['A community of bodybuilders, gym-goers, and like-minded people!',
 'Texas Convergent is an entrepreneurial, product-building organization at UT Austin. We provide students the necessary skills and resources to drive the future of innovation through a hands-on, project-based curriculum.',
 'We promote data science and machine learning through our general meetings every Tuesday at 7 pm. These meetings include technical workshops, career advice, industry speakers, and socials. We also host the Deep Learning Workshop Series, Long Competition, and Datahack.',
 'Women in Computer Science is a non-profit organization dedicated to building a community of women in Computer Science.']

In [10]:
student_interest_text = " ".join(my_interests)
student_interest_text

'Computer Science Fitness Biological Sciences Technology'

In [11]:
documents = [student_interest_text] + org_descriptions
documents

['Computer Science Fitness Biological Sciences Technology',
 'A community of bodybuilders, gym-goers, and like-minded people!',
 'Texas Convergent is an entrepreneurial, product-building organization at UT Austin. We provide students the necessary skills and resources to drive the future of innovation through a hands-on, project-based curriculum.',
 'We promote data science and machine learning through our general meetings every Tuesday at 7 pm. These meetings include technical workshops, career advice, industry speakers, and socials. We also host the Deep Learning Workshop Series, Long Competition, and Datahack.',
 'Women in Computer Science is a non-profit organization dedicated to building a community of women in Computer Science.']

In [12]:
vectorizer = TfidfVectorizer(stop_words='english')
vectorizer

TfidfVectorizer(stop_words='english')

In [14]:
tfidf_matrix = vectorizer.fit_transform(documents)
print(tfidf_matrix)

  (0, 53)	0.4428321995085722
  (0, 46)	0.4428321995085722
  (0, 3)	0.4428321995085722
  (0, 18)	0.4428321995085722
  (0, 45)	0.2965698850220162
  (0, 9)	0.35727423026525224
  (1, 37)	0.38775666010579296
  (1, 33)	0.38775666010579296
  (1, 29)	0.38775666010579296
  (1, 21)	0.38775666010579296
  (1, 22)	0.38775666010579296
  (1, 4)	0.38775666010579296
  (1, 7)	0.3128396318588854
  (2, 11)	0.22761492325233004
  (2, 2)	0.22761492325233004
  (2, 41)	0.22761492325233004
  (2, 23)	0.22761492325233004
  (2, 27)	0.22761492325233004
  (2, 19)	0.22761492325233004
  (2, 16)	0.22761492325233004
  (2, 44)	0.22761492325233004
  (2, 48)	0.22761492325233004
  (2, 34)	0.22761492325233004
  (2, 51)	0.22761492325233004
  (2, 43)	0.22761492325233004
  :	:
  (3, 50)	0.1842758019271211
  (3, 26)	0.1842758019271211
  (3, 0)	0.1842758019271211
  (3, 6)	0.1842758019271211
  (3, 59)	0.1842758019271211
  (3, 52)	0.1842758019271211
  (3, 25)	0.1842758019271211
  (3, 38)	0.1842758019271211
  (3, 55)	0.1842758019271

In [15]:
cosine_similarities = cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:])
cosine_similarities

array([[0.        , 0.        , 0.03660018, 0.26649462]])

In [18]:
# some way of combining the category + tfidf methods to make a composite score?
pcts + cosine_similarities

array([[0.25      , 0.5       , 0.53660018, 0.76649462]])

In [22]:
# think I'd like to weigh the intersection scores more
intersection_weight = 0.8
cosine_weight = 0.2

(np.asarray(intersection_weight) * pcts) + (np.asarray(cosine_weight) * cosine_similarities)

array([[0.2       , 0.4       , 0.40732004, 0.45329892]])

In [23]:
# yeah i'm chillin w that, too tired to think of anythng else rlly

SyntaxError: invalid syntax (372171682.py, line 1)